# Generated by Django 2.0.7 on 2018-08-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0003_auto_20180810_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
