# Generated by Django 2.0.7 on 2018-09-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0004_remove_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
