# Generated by Django 2.0.7 on 2018-09-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0007_auto_20180924_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
