# Generated by Django 2.0.7 on 2018-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative', '0008_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
